### ISSUE TITLE
The Installad Capacity in Germany of the coal power plants isnt correct

### ISSUE THREAD

**Issue by moinmoin2** [tmrowco/electricitymap-contrib#3067] opened 2021-03-25 13:00 UTC
To the year 2021 some coal power plants in germany were shuted down permantnently and will be decommissioning. For example Niederaußem D is permanently shuted down

**Comment by FelixDQ** [comment] 2021-03-25 13:11
Thanks @moinmoin2!

I think this is a duplicate of https://github.com/tmrowco/electricitymap-contrib/issues/3067

Feel free to open a PR with the changes or add more information to the other issue :-)

**Closed by FelixDQ** 2021-03-25 13:11 UTC
