### ISSUE TITLE
Update the screenshoot into README

### ISSUE THREAD

**Issue by Manu1400** [tmrowco/electricitymap-contrib#2918] opened 2021-01-12 10:28 UTC
The screenshoot of the website in README is 3 years old !

sources  : 
* git blame, line 7 : https://github.com/tmrowco/electricitymap-contrib/blame/master/README.md
* diff : https://github.com/tmrowco/electricitymap-contrib/commit/03b5c31f6b05caaaf3917f15d570eb1c113cf21c

More countries is supported now (and the UI have now a "production / consumption" button).

**Comment by veqtrus** [comment] 2021-01-23 16:24
`<meta property="og:image" content="https://www.electricitymap.org/images/electricitymap_social_image.jpg" />` should also be updated.

**Comment by Manu1400** [comment] 2021-01-23 18:14
> `<meta property="og:image" content="https://www.electricitymap.org/images/electricitymap_social_image.jpg" />` should also be updated.

It's the same URL

**Comment by corradio** [comment] 2021-02-10 14:47
duplicate of https://github.com/tmrowco/electricitymap-contrib/issues/2617

**Closed by corradio** 2021-02-10 14:47 UTC
