### ISSUE TITLE
Add CH4 emissions to electrecity map

### ISSUE THREAD

**Issue by MehdiLarnaout** [tmrowco/electricitymap-contrib#3082] opened 2021-04-05 23:09 UTC
Hello, 

I've been browsing electrecity map for over a year now, enjoying seeing where my country (France) stands all the time, and it's while looking at a simple graph of greenhouse gas emissions (including CH4 leakage emissions) from each method of electricity production that I ask if it's possible to add them to electrecity map.

The interest here is to show a little more the reality of the harmful effects of fossil resources, especially concerning natural gas, which many countries praise in comparison to coal... only by looking at the CO2 emissions.
The problem is that if we look at all the greenhouse gas emissions (CO2+CH4), natural gas is almost at the same level as coal, with the difference that CH4 has a more powerful greenhouse effect.

![20210406_024132](https://user-images.githubusercontent.com/44522128/113643674-1f99fe00-9683-11eb-889f-d1bf4d944eff.jpg)

![EjQ7FXmWsAACstp](https://user-images.githubusercontent.com/44522128/113644270-b31ffe80-9684-11eb-8a27-8822d994fa40.jpg)

![EjTQZpaXkAEJlUQ](https://user-images.githubusercontent.com/44522128/113647894-f9c52700-968b-11eb-8a53-c46709a7de19.jpg)

It is quite striking because even if methane has an effect that lasts ~12 years on the atmosphere (and because unfortunately natural gas power plants will not close in 12 years), we know that it is still 25 times more potent than carbon dioxide in terms of global warming potential (GWP).
So, we can come to the conclusion that at the moment natural gas is worse than coal because the methane leakage are much more important than for the others method of electrecity production (!)

Looking only at CO2 emissions is, I think, a big mistake. 

I hope that I have convinced you of the interest of this proposal, please accept my best regards,

M. Larnaout

**Comment by jarek** [comment] 2021-04-06 01:57
Electricity Map uses CO2eq figures, meaning "equivalent", and I think that this includes the proportional impact of CH4?

You can see more info at https://github.com/tmrowco/electricitymap-contrib/wiki/Carbon-intensity-calculations and https://github.com/tmrowco/electricitymap-contrib/wiki/Emission-factors . The CO2eq values are from IPCC 2014 report mentioned in the Emission factors page. Do you think that the "natural gas" CO2eq value found in the IPCC report should not be used?

**Comment by MehdiLarnaout** [comment] 2021-04-06 02:11
@jarek No, the IPCC report does not include CH4 emissions because it would then have been specified !
Only CO2 emissions are mentioned in the IPCC report, for the sources you have used.

It would then have to be added next to the CO2eq/kWh emissions, so we would have the CH4eq/kWh emissions.

I fear that this would be complex to add (in terms of coding) to the electricity map program but it seems important to me because many countries and industries only take CO2 into account when it comes to gas.

I have added 3 graphs to my commentary (with the sources indicated) which summarise the subject, including methane leakage, and which should help you if you are interested in my proposal.

**Comment by MehdiLarnaout** [comment] 2021-04-06 02:25
@jarek I just realised that I could have written my message in the Pull requests tab, I'm sorry 😅

**Comment by corradio** [comment] 2021-04-06 06:44
> @jarek No, the IPCC report does not include CH4 emissions because it would then have been specified !
> Only CO2 emissions are mentioned in the IPCC 2014 report, for the sources you have used for electrecity map

Hi @MehdiLarnaout ,
As @jarek explained, the IPCC figures that we use include the global forcing caused by methane.
As you'll see in [this link](https://en.wikipedia.org/wiki/Life-cycle_greenhouse_gas_emissions_of_energy_sources), the unit is in `co2eq` which is a unit that includes the warming potential of methane (https://ec.europa.eu/eurostat/statistics-explained/index.php/Glossary:Carbon_dioxide_equivalent)

**Comment by MehdiLarnaout** [comment] 2021-04-06 08:40
Hi @corradio @jarek ,

I'm sorry but I think you are mistaken.

I double checked the 2014 IPCC A and B reports with the help of the search bar and nowhere does it say that CO2eq means CO2+CH4.

Yet the sources you take to define fossil resource emissions only take CO2 into account as shown on the many graphs in the IPCC reports. CO2 is CO2 and CH4 is CH4, in a report of excellence like those of the IPCC, they cannot write that CO2eq means CO2+CH4eq emissions, in which case I think they would have invented a new value to quantify these 2 greenhouse gases.

I invite you to check this for yourself.

Note that if you don't want to take into account CH4 emissions in the electrecity map, that's fine but it's just a shame to take into account only part of the reality.
You are already doing a great job in making CO2 data available to the general public.

M.

**Comment by corradio** [comment] 2021-04-06 08:51
Hi @MehdiLarnaout ,

It is definitely our wish to take into account all GHG (including methane), so don't worry: our intentions align!
By definition, CO2eq includes all GHG (including methane).

In the [IPCC report](https://www.ipcc.ch/site/assets/uploads/2018/02/ipcc_wg3_ar5_annex-iii.pdf#page=7) used, you can see it uses CO2eq, and you can see methane emissions.

![image](https://user-images.githubusercontent.com/1655848/113684350-6dcff100-96c5-11eb-9ed0-b837aa52670a.png)

In the [methodology](https://www.ipcc.ch/site/assets/uploads/2018/02/ipcc_wg3_ar5_annex-ii.pdf), page 27, you can see it explicitly says it takes into account methane:
![image](https://user-images.githubusercontent.com/1655848/113684625-b7b8d700-96c5-11eb-8586-d39836ea3d1a.png)


Note that we plan to move away from IPCC 2014 as it is a very outdated source, and some sources of methane emissions might have been missed. Note nonetheless that electricityMap does its best to track methane emissions and that's why we use the CO2eq metric instead of just CO2.

**Comment by MehdiLarnaout** [comment] 2021-04-06 09:01
@corradio Thank you very much for this clarification.
I admit that I focused too much on the term CO2eq, thinking that it only took into account CO2.

Note that I was talking mainly about methane leakage, which is a criticism that I see coming up a lot when it comes to the IPCC.
So it's good that you're moving away from the 2014 IPCC reports because indeed some greenhouse gas emissions are being omitted. 

I urge you to continue on this path and thank you again. 

Translated with www.DeepL.com/Translator (free version)

**Comment by corradio** [comment] 2021-04-06 10:37
Great! Ill close this issue for now then.

**Closed by corradio** 2021-04-06 10:37 UTC
Labels: science
