### ISSUE TITLE
Please divide Sweden into four electricity areas! Compare with Norway.

### ISSUE THREAD

**Issue by Blixtmannen** [tmrowco/electricitymap-contrib#2616] opened 2020-08-10 11:56 UTC
Dear Sir,

I like you map BUT: Please divide Sweden into four electricity areas! Compare with Norway.

Best

Magnus

**Comment by magol** [comment] 2020-08-10 12:44
This is a duplicate of #1397

Unfortunately, the work with #1397 seems to have stopped, but I hope it can start again.

**Comment by martincollignon** [comment] 2020-08-10 12:54
Closing as it is a duplicate.

**Closed by martincollignon** 2020-08-10 12:54 UTC
