### ISSUE TITLE
Northwest USA - Bonneville Power Administration (BPA)

### ISSUE THREAD

**Issue by systemcatch** [tmrowco/electricitymap-contrib#1040] opened 2018-01-29 10:34 UTC
There is 5 minute data broken down by type at https://transmission.bpa.gov/business/operations/Wind/baltwg.aspx

BPA covers several states in the Northwest US.

![bpa](https://user-images.githubusercontent.com/30196510/35506011-dba36fa2-04df-11e8-8dca-9e41c9d064cf.png)

**Comment by alixunderplatz** [comment] 2018-01-29 12:16
These borders of BPA are gratifiying 🙏 
Is that an old map ... what happened to MISO ??? 🤣 😆 

BPA have a geoportal:
http://bpagis.maps.arcgis.com/home/index.html

I assume, the grey lines are their balancing territory now?

![image](https://user-images.githubusercontent.com/25743609/35509997-8fe80bd8-04f6-11e8-8415-89a12b95ea4b.png)

**Comment by alixunderplatz** [comment] 2018-01-29 12:28
That BPA area seems to have huge generation excess (> 6GW), any infos on their site on power flows?

The DC line that is pointing to the upper left corner of Nevada in the image above is this one:
https://en.wikipedia.org/wiki/Pacific_DC_Intertie
It's going to the LA area and has 3100 MW transmission capacity

**Comment by HansHyde** [comment] 2018-01-29 12:29
BPA is a federal owned agency (like a Canadian "Crown" Company), that is only generation & transmission.

They, like TVA, generate & sell wholesale to any number of MOUs, Co-Ops, IOUs where their transmission lines cross-over.  At least 1/2 of the grey border territory above is PacifiCorp (IOU) - not a lot of people, but a large part of the land area.

**Comment by HansHyde** [comment] 2018-01-29 12:58
The ISO Today app (CAL-ISO website) shows the wholesale prices of every "Node", where a "Node" is a substation, switchyard or step-up sub at a generation station, for the entire Western EIM (Electricity Imbalance Market).  Nodes data is available in realtime, 5 minute frequency.

Prices & Congestion at Nodes does not tell flows, but it does offer clues as to how the system is operating.  How to convert that to flows (for use within EM) is beyond me, but there are 100s (thousands?) of Nodes that will ultimately determine 1) the generators (for the generation mix applicable) & 2) the end customers (regions of consumption applicable).

IMHO EM Parsers & their json territories are not designed for this, so not certain how the data can/will be scraped & parsed.

As I said some time ago, BPA does not have a customers per se territory, it is simply a transmission network that crosses over everything and supplies small to large electric distribution entities, while managing a fleet of generation assets (primarily, but not exclusively, hydro on the Columbia.

There are some 100 main (longer distance) transmission lines (all numbered) in the Western Grid, both AC & DC.  If data, specifically flow, was to be found upon them, one option might be able to build a functional network of "EM Exchanges" to underly the map & json territories and plug that into unseen Parsers (such as BPA) when GenMix data is available.

![weim - caiso_nodes - physical_electricgrid_assets](https://user-images.githubusercontent.com/33690988/35511402-085d0e24-04fc-11e8-9cb0-8afae1f0e8ce.png)

![weim-moonshin_node2](https://user-images.githubusercontent.com/33690988/35511409-12d7047c-04fc-11e8-8cb3-abf5c66fb233.png)


![weim - moonshine substation - connection point to windfarm](https://user-images.githubusercontent.com/33690988/35511411-1d234a80-04fc-11e8-96e1-baaa3b3a3675.png)

**Comment by systemcatch** [comment] 2018-01-29 18:15
Interesting, we'll have to think carefully about how we represent this on the map. The parser should be easy enough to write though.

**Comment by systemcatch** [comment] 2018-04-27 09:53
The parser is basically built and working, we just need to figure out how we want this to appear on the map.

@alixunderplatz any thoughts?

**Comment by alixunderplatz** [comment] 2018-04-27 11:27
@systemcatch maybe is makes sense to merge BPA (US-OR & US-WA) with Idaho?

The northern part of Idaho isn't really covered by IPC, but by BPA.
https://bpagis.maps.arcgis.com/apps/webappviewer/index.html?id=275cd78c003349719b28f7130d4b933e


Here is a merged map of [BPA's **renewable** generation assets](https://bpagis.maps.arcgis.com/apps/webappviewer/index.html?id=43e1c8ed8ad44e4b8890d2e870b591b4) and their power lines:

![image](https://user-images.githubusercontent.com/25743609/39360302-048f5f24-4a1e-11e8-8804-a544cd4fe821.png)

Their RES capacity is located in the core of the area, some even in the South of Idaho.
Most of IPC's generation equipment was located in the southern part of Idaho, but some of it was also in the state of Oregon, if I remember correctly.

I wouldn't mind the few hydro power plants in Monatana, these have about 250 MW.

I think that's a good way to get rid of some uncertainties caused by the incoherent covered areas of BPA and IPC. I hadn't yet looked at the installed solar and wind capacity in IPC's area, but I assume most of it running under "power purchase agreements" is in that area anyway, so we could finally also include all these on the map and merge them with BPA's production data.

Here's the map from EIA with all the related generators and transmission lines:
![image](https://user-images.githubusercontent.com/25743609/39360230-b9431a4c-4a1d-11e8-9efe-b5c43ecc9d56.png)

**Comment by alixunderplatz** [comment] 2018-04-27 11:43
@systemcatch the only thing that worries me is that their balancing authority area (thick grey outlines in the upper image) - unlike their grid - is entirely including Idaho as well. We need to make sure what their generation data really represents. It could be that IPC's generation data is also included in what BPA is reporting.

**Comment by systemcatch** [comment] 2018-04-28 12:37
Looking at the list of plants on https://transmission.bpa.gov/business/operations/Wind/baltwg.aspx and https://www.idahopower.com/energy/delivering-power/power-plants/ I don't see any overlap in plants (maybe wind) and both sources only seem to report their own generation.

**Comment by jarek** [comment] 2018-04-28 12:51
I'm not sure if we can show BPA as including all of Washington and Oregon. Some of https://en.wikipedia.org/wiki/List_of_power_stations_in_Oregon#Fossil_fuel as well as https://en.wikipedia.org/wiki/Centralia_Power_Plant seem to be missing from the list of plants in https://transmission.bpa.gov/business/operations/Wind/baltwg.aspx

**Comment by systemcatch** [comment] 2019-08-19 09:45
Might be some historical exchanges at https://transmission.bpa.gov/Business/Operations/Paths/default.aspx

**Comment by corradio** [comment] 2020-01-06 13:24
Closing due to inactivity. Thank you all for your inputs!

**Closed by corradio** 2020-01-06 13:24 UTC
Labels: parser
