### ISSUE TITLE
Ireland is missing

### ISSUE THREAD

**Issue by DavidWeather** [tmrowco/electricitymap-contrib#2037] opened 2019-10-17 13:41 UTC
Ireland (Republic) was working perfectly until this week.

Some data available here http://smartgriddashboard.eirgrid.com/ and http://live.windenergy.ie/

**Comment by jarek** [comment] 2019-10-17 13:54
Hi, thanks for noticing! We do indeed have Ireland normally.

[Kibana logs](https://kibana.electricitymap.org/app/kibana#/discover/10af54f0-0c4a-11e9-85c1-1d63df8c862c?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:now-24h,mode:quick,to:now))&_a=(columns:!(message,extra.key,level),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'96f67170-0c49-11e9-85c1-1d63df8c862c',key:level,negate:!f,params:(query:ERROR,type:phrase),type:phrase,value:ERROR),query:(match:(level:(query:ERROR,type:phrase))))),index:'96f67170-0c49-11e9-85c1-1d63df8c862c',interval:auto,query:(language:lucene,query:IE),sort:!('@timestamp',asc))) have seemingly unrelated errors, like:

October 16th 2019, 13:03:42.380 `query_production` failed in ENTSOE.py. Reason: Max allowed requests per minute from each unique IP is max up to 400 only

[That error seems to be logged about 5000 times in past 24 hours](https://kibana.electricitymap.org/app/kibana#/discover/10af54f0-0c4a-11e9-85c1-1d63df8c862c?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:now-24h,mode:quick,to:now))&_a=(columns:!(message,extra.key,level),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'96f67170-0c49-11e9-85c1-1d63df8c862c',key:level,negate:!f,params:(query:ERROR,type:phrase),type:phrase,value:ERROR),query:(match:(level:(query:ERROR,type:phrase))))),index:'96f67170-0c49-11e9-85c1-1d63df8c862c',interval:auto,query:(language:lucene,query:'%22failed%20in%20ENTSOE.py.%20Reason:%20Max%20allowed%20requests%20per%20minute%20from%20each%20unique%20IP%20is%20max%20up%20to%20400%20only%22'),sort:!('@timestamp',asc)))

**Comment by jarek** [comment] 2019-10-18 00:04
Hi David, if my interpretation is correct and this is related to ENTSOE: ENTSOE is the EU-wide electricity data platform - the issue is with how Electricity Map queries it. So in that case not something that the Irish data provider would be responsible for.

**Comment by corradio** [comment] 2019-10-18 07:12
You are right. We've just reached out to ENTSOE to fix this. cc @tth4vb

**Comment by corradio** [comment] 2019-10-18 19:26
Fixed

**Comment by DavidWeather** [comment] 2019-10-21 15:29
Has anyone contacted ENTSOE in Belgium? Ireland is still grey on the map. I wonder are they aware of this problem?

**Comment by chrismcg** [comment] 2019-11-04 20:47
While ideally the data would find its way back into ENTSOE I have data scraped from http://smartgriddashboard.eirgrid.com/ here: https://sg.chrismcg.com. It's behind a GraphQL API at the moment but I could easily add another output format if that was useful.

**Comment by systemcatch** [comment] 2019-11-05 10:45
@chrismcg thanks for scraping that, Ireland looks to be working again on the map.

**Comment by alixunderplatz** [comment] 2019-11-13 21:04
Ireland is up and running again, so I'll close this issue. We can keep the dashboard in mind as alternative datasource. I will add it to #1015 one day

**Closed by alixunderplatz** 2019-11-13 21:04 UTC
