### ISSUE TITLE
Australia rooftop solar and interconnector missing 

### ISSUE THREAD

**Issue by McPeter54** [tmrowco/electricitymap-contrib#3222] opened 2021-07-18 14:37 UTC
There is only utility solar generation shown in the Australian zones. Rooftop solar is missing and that’s a big part of the solar generation so it would be nice to add that.

The interconnector between South Australia and Victoria isn‘t shown on the map. OpenNem reports power being transferred but there’s no arrow on the map.

**Comment by jarek** [comment] 2021-07-18 18:30
i see following logs for  AUS-NSW->AUS-VIC, but I'm not sure what's causing it yet:

```
  File "/home/src/electricitymap/contrib/parsers/OPENNEM.py", line 240, in fetch_exchange
    df = fetch_main_df('power', sorted_zone_keys=sorted_zone_keys, session=session, target_datetime=target_datetime, logger=logger)
  File "/home/src/electricitymap/contrib/parsers/OPENNEM.py", line 126, in fetch_main_df
    df = pd.concat([dataset_to_df(ds) for ds in filtered_datasets], axis=1)
  File "/usr/local/lib/python3.7/site-packages/pandas/core/reshape/concat.py", line 225, in concat
    copy=copy, sort=sort)
  File "/usr/local/lib/python3.7/site-packages/pandas/core/reshape/concat.py", line 259, in __init__
    raise ValueError('No objects to concatenate')
ValueError: No objects to concatenate
```

**Comment by pbubik** [comment] 2021-07-30 16:58
Rooftop solar (and micro hydro) is an issue in all other jurisdictions, though admitedly probably smaller than in Australia. We can't and shouldn't expect tiny projects to report their production data, because that would kill many of them. They are accounted for in load data. They decrease their own load, and if they are spilling onto the grid, are reducing the load of their neighbours. (Keep in mind house meters are not reported in transmission data either - load of residential areas is typically measured at a substation level or a distributor's point of interconnection (POI) ). So until we see significant amounts of zero or negative loads being reported in a juridstiction (show me one), I wouldn't worry about trying to account for rooftop solar.
For example, in Alberta Canada (the sunniest province in Canada) the rooftop solar installations account for about 20MW. On a grid with normal load around 10 000 MW, this is really quite insignificant. The data doesn't get ignored, the data is baked in as negative load... which is the best load to have. :)

**Comment by jarek** [comment] 2021-07-31 02:03
Australia parsers previously reliably reported fairly good estimates of rooftop solar generation, so the issue is something broke here.

**Comment by Manu1400** [comment] 2021-07-31 15:53
AUS-VIC->AUS-SA is visible in widget https://www.reddolphin.com.au/widget_whaven/

**Comment by LukePrior** [comment] 2021-09-05 07:27
You can see the small scale solar in this widget: http://reneweconomy.com.au/nem-watch/

**Comment by CloCkWeRX** [comment] 2021-10-04 04:37
>The interconnector between South Australia and Victoria isn‘t shown on the map. OpenNem reports power being transferred but there’s no arrow on the map.

Is this still the case? I see:

![image](https://user-images.githubusercontent.com/365751/135795138-04c23a1a-314f-4d0d-9d15-3be685adbe65.png)

**Comment by simonhac** [comment] 2021-10-05 10:30
the OpenNEM endpoint that is supposed to vend `solar_rooftop` is not emitting series for NSW, QLD, VIC, SA and TAS.

i've filed https://github.com/opennem/opennem/issues/40 which should hopefully be fixed soon.

**Comment by KabelWlan** [comment] 2021-11-10 09:50
This seems to be fixed now.

![Unbenannt](https://user-images.githubusercontent.com/49598085/141090427-ed16b72e-56ca-4cba-8576-39a223796f31.png)

**Closed** 2021-12-01 10:22 UTC
