### ISSUE TITLE
CH gen source "unknown"

### ISSUE THREAD

**Issue by dguzs** [tmrowco/electricitymap-contrib#2930] opened 2021-01-16 09:59 UTC
Hello,

Very glad to see Switzerland appearing in the map.

Switzerland has only nuclear and hydro generation. Right now 24% of generation is "unknown" source with large CO2 emissions, despite that Switzerland does not have any large fossil generation. So this "unknown" are very probably hydro power plants.

Would it be possible to categorize "unknown" in CH as hydro, or any other similar solution?

**Comment by corradio** [comment] 2021-01-16 10:15
Duplicate of https://github.com/tmrowco/electricitymap-contrib/issues/2929

**Closed by corradio** 2021-01-16 10:15 UTC
