### ISSUE TITLE
Germany <-> Norway HVDC cable NordLink entering test phase

### ISSUE THREAD

**Issue by Gazer75** [tmrowco/electricitymap-contrib#2698] opened 2020-09-28 15:06 UTC
NordLink is now in testing phase and should be in full operation by December 2020.

Needs to be added to the parser and visually on map.

**Comment by brandongalbraith** [comment] 2020-09-28 15:22
Duplicate of https://github.com/tmrowco/electricitymap-contrib/issues/2647, already closed by https://github.com/tmrowco/electricitymap-contrib/pull/2648

**Comment by Kongkille** [comment] 2020-09-28 15:27
Yes, the reason why it's not showing is likely because it's very low. I'm pretty sure it has been visible a couple of times

cc @FelixDQ

**Closed by Kongkille** 2020-09-28 15:27 UTC

**Comment by Gazer75** [comment] 2020-09-28 15:50
Still missing the detail in each region. Those should be visible even if 0

**Comment by Gazer75** [comment] 2020-09-28 15:52
This should be changed IMO. Removing the arrows with no transfer is confusing and leads to reports like this...
