### ISSUE TITLE
Wrong direction on export from Poland to Sweden

### ISSUE THREAD

**Issue by LucasCarlsson** [tmrowco/electricitymap-contrib#2061] opened 2019-10-23 18:50 UTC
In the App Poland exports electricity to Sweden. On the Swedish powergrid homepage (https://www.svk.se/drift-av-stamnatet/kontrollrummet/) it´s Sweden that´s exporting to Poland.

**Comment by alixunderplatz** [comment] 2019-10-23 19:00
duplicate of #2052

**Closed by alixunderplatz** 2019-10-23 19:00 UTC
