### ISSUE TITLE
Imports for California not showing on graph

### ISSUE THREAD

**Issue by q--** [tmrowco/electricitymap-contrib#2472] opened 2020-05-04 20:18 UTC
[As I noted on Slack on April 29](https://tmrow-team.slack.com/archives/C2DQPTHA6/p1588173873258300)

>Mousover of the arrow on the map shows that California is importing 4302MW from the rest of the U.S. right now, but it isn't showing up on the graph

>https://www.electricitymap.org/zone/US-CAL-CISO

The issue is still present; 1080MW of imports, but nothing on the graph.

**Comment by jarek** [comment] 2020-05-05 00:28
To fix this, we need to change https://github.com/tmrowco/electricitymap-contrib/blob/c5d983331d8bcd62b76382f3dd33ac6fb1f7d942/config/exchanges.json#L2296 to refer to `US-CAL-CISO` rather than `US-CA`.

But while we're here, it might be worth it to see if we can find out where exactly those imports are coming from and if they can be refined per source (e.g. how much from Nevada vs how much from Desert Southwest vs whatever the source in the north is)?

**Comment by robertahunt** [comment] 2020-05-05 08:30
This is because we have two 'versions' of the US in electricitymap at the moment - the old version with all of its old imports (including US->US-CA) and the new version with US-CAL-CISO, which has exchanges defined to each of the other balancing authorities that it is connected to - unfortunately the new exchange data comes from EIA at the moment so it is too delayed to show up on the live map, but is important for our historic data. If real-time exchange data is available from CISO, we could add this to the map and then these would show up properly.

The problem is really that we have these two versions of the US running at the moment, and that the exchanges from both versions show up on the map. We should be able to totally remove the old US zones in the coming weeks, and then this will no longer be an issue. In the meantime I am sorry for all the confusion this has created.

**Comment by FelixDQ** [comment] 2020-07-02 08:28
I'm closing this issue as the removal of old us zones is tracked in our internal repo https://github.com/tmrowco/tmrow/issues/3177

**Closed by FelixDQ** 2020-07-02 08:28 UTC
Labels: bug 🐞

**Comment by q--** [comment] 2020-09-09 13:47
FYI this is still happening. With >10GW of imports right now and record consumption amid the heat wave, it's a pity CA's carbon intensity isn't calculated accurately

**Comment by FelixDQ** [comment] 2020-09-09 14:00
Yea it's unfortunate. We have had some delays in fully migrating to the new US zones, and it will probably be a month or two before we cal fully remove the old US zones.

**Comment by q--** [comment] 2020-09-09 16:37
Glad to hear you're still working on this, thanks
