### ISSUE TITLE
Look into potentially broken navigation bar for the iOS app on iPhone 12?

### ISSUE THREAD

**Issue by madsnedergaard** [tmrowco/electricitymap-contrib#3034] opened 2021-03-11 14:11 UTC
## Description

A user reported that the navigation bar isn't working properly on the iOS app on iPhone 12.

Can anyone with an iPhone 12 and the electricityMap app installed help with testing this? :)

![Screenshot 2021-03-11 at 15 09 59](https://user-images.githubusercontent.com/3296643/110799845-e5a02c80-827b-11eb-8f0f-318c205a57b2.png)

**Comment by hybridcattt** [comment] 2021-04-22 19:00
This is how it looks on iPhone XS, and any model in the same line newer than iPhone X released in 2017. My guess would be that it's what the user means. I've noticed before too. 
iPhone screenshots don't include the notch and the home indicator, hence the IRL device pics. 

I'm wrapping up a fix - PR coming soon :) 

![IMG_0007 (1)](https://user-images.githubusercontent.com/11408899/115770358-e06eeb00-a3ac-11eb-87a9-a0d581fc9fe1.jpeg)
![IMG_0008 (1)](https://user-images.githubusercontent.com/11408899/115770361-e238ae80-a3ac-11eb-90e4-05a1b976419a.jpeg)
![IMG_0009 (1)](https://user-images.githubusercontent.com/11408899/115770364-e369db80-a3ac-11eb-9ae5-286dd79587f1.jpeg)

**Comment by martincollignon** [comment] 2021-04-22 19:31
Yayyy!

**Comment by skovhus** [comment] 2021-05-06 18:59
#3109 seems to have introduced a regression on devices without notch, the padding to the status bar needs to be taken into account. I'm wondering if we should simply disable the status bar as the coloring doesn't work. 

@hybridcattt 

![IMG_0638](https://user-images.githubusercontent.com/1260305/117347046-db2f9700-aea8-11eb-929f-671087cde166.PNG)

I finally got my simulator setup up and running (after mergin #3109 – I took a chance). There also seems to be an issue here:
<img width="528" alt="Screenshot 2021-05-06 at 20 56 40" src="https://user-images.githubusercontent.com/1260305/117351256-c99cbe00-aead-11eb-9715-f0580babd218.png">

**Comment by hybridcattt** [comment] 2021-05-06 19:22
This definitely works (worked), and I tested on multiple devices incl. no-notch. What I see  in your screenshots is that no padding is applied at all, on either of screen types - that means it's most likely a setup issue and not something in code/CSS that doesn't work only in specific cases :) 

Here's a bunch of screenshots I have lying around (I think I meant to attach them to the PR hehe)

I'll have a quick look as soon as I can, must be some small issue messing with everything 🤞 

<img width="502" alt="Screenshot 2021-04-22 at 18 15 39" src="https://user-images.githubusercontent.com/11408899/117353497-79732b00-aeb0-11eb-8cb7-cc172a8303fc.png">
![Uploading Screenshot 2021-04-22
<img width="546" alt="Screenshot 2021-04-22 at 18 16 41" src="https://user-images.githubusercontent.com/11408899/117353503-7b3cee80-aeb0-11eb-881f-e49db3e21ea3.png">
 at 18.16.25.png…]()

<img width="546" alt="Screenshot 2021-04-22 at 18 05 05" src="https://user-images.githubusercontent.com/11408899/117353492-7710d100-aeb0-11eb-99a3-8967d664e7fd.png">

**Comment by skovhus** [comment] 2021-05-06 19:24
Thanks! I think I found the issue, see https://github.com/tmrowco/electricitymap-contrib/pull/3109#discussion_r627696129

**Comment by corradio** [comment] 2021-05-25 05:56
@skovhus did we end up fixing it?

**Comment by skovhus** [comment] 2021-05-25 06:46
Yes, it was fixed. :)

**Closed by skovhus** 2021-05-25 06:46 UTC
Labels: bug 🐞, help wanted, mobile app 📱
