### ISSUE TITLE
Ranking in view with detailed production bars. 

### ISSUE THREAD

**Issue by karsten-brauner** [tmrowco/electricitymap-contrib#2179] opened 2020-01-21 20:54 UTC
This is an idea to improve the view you got when you point out a region on the map. I think it will be a useful argument in climate debat if you near carbon intensity display current ranking. It could also be a choise to see ranking on the map so its easy to benchmark regions in a narrow map wiev. Specialy region located in sea like Denmark and islands can be diffycult to valute on colours only.

**Comment by robertahunt** [comment] 2020-01-22 13:12
Could you elaborate more on your suggestion and why you think it would help the climate debate? From my understanding, you would like us to show the region's current ranking close to the carbon intensity display? This could be interesting. 

For the second suggestion, you think we should to show the country's ranking on top of the country on the map? From a design standpoint I think this could get cluttered, but that is just my opinion. I am curious to hear other's opinion on this.

**Comment by fbarl** [comment] 2020-05-08 15:37
Thanks for your suggestion @karsten-brauner!

I personally like the idea of adding zone carbon ranking information to the map tooltips, but agree with @robertahunt that the UI might be too clutered if we'd render it directly on the map.

I'd be happy to give this idea a quick try!

**Comment by pierresegonne** [comment] 2020-07-02 11:01
I am not sure to understand what is suggested here. @fbarl did you give the idea a try?

If no action point is clearly stated I'll close the issue ;)

**Comment by fbarl** [comment] 2020-07-29 18:00
@pierresegonne The issue is somewhat vague indeed. I didn't try making any changes yet, partly because I was hesitant to significantly modify the UI without a clear objective in mind or at least more upvotes from the community.

I'll let @FelixDQ and @Kongkille make the final call, but as far as I'm concerned we can close this issue :slightly_smiling_face:

**Comment by Kongkille** [comment] 2020-07-29 18:15
Yes, thanks for the suggestion @karsten-brauner!

However, In my opinion, I don't think we should push the idea of ranking countries further. We already have some sort of ranking in the area overview and I think it is somewhat presumptuous, and not really our purpose, to create definitive rankings. For example, Bornholm tends to be number 1, but it is a really small zone, relying a lot on imports from Sweden (and I am even biased since I am from there!)

If anyone disagrees, feel free to reopen the issue but I am going to close it for now :)

**Closed by Kongkille** 2020-07-29 18:15 UTC
Labels: frontend 🎨, idea 💡
