### ISSUE TITLE
Netherlands: wrong fossil gas live production data

### ISSUE THREAD

**Issue by Kevindeving** [tmrowco/electricitymap-contrib#2431] opened 2020-04-27 19:48 UTC
Netherlands in electricitymap displays wrong (lower than actual entsoe production) on electricitymap for whatever weird reason. I have been seeing this for a long time now.

For example right now (27.04.2020 GMT+1 evening) 

Electricitymap: about 1.6GW

Entsoe data: about 4GW

**Comment by alixunderplatz** [comment] 2020-04-27 20:13
Hi @Kevindeving , thanks for this note. 
I think the data on entsoe for NL's gas production was kind of weird. in the past there was a category "fossil gas consumption" which was higher than 1GW all the time (usually this category would make sense for the self consumption of the plants like pumped storage).
Can you crosscheck if entsoes "fossil gas - fossil gas consumption" euqals the values displayed on electricityMap? this would help a lot and this could be reported to entsoe.
there is a long "battle" going on to finally get the Dutch data right. see one of the oldest issues: #78

**Comment by Kevindeving** [comment] 2020-04-27 20:35
> Hi @Kevindeving , thanks for this note.
> I think the data on entsoe for NL's gas production was kind of weird. in the past there was a category "fossil gas consumption" which was higher than 1GW all the time (usually this category would make sense for the self consumption of the plants like pumped storage).
> Can you crosscheck if entsoes "fossil gas - fossil gas consumption" euqals the values displayed on electricityMap? this would help a lot and this could be reported to entsoe.
> there is a long "battle" going on to finally get the Dutch data right. see one of the oldest issues: #78

This is a long discussion indeed. I am reading through this now.

And indeed fossil gas consumption shows like 2.4GW right now which lowers the electricitymap value. I think this is really going wrong and we should add this consumption instead. To me it looks like it has to do more with production as it ramps up with production, too, but at least it doesn't make sense to subtract it from production. Also this would make more sense regarding Netherlands Electricity mix and high amount of gas plants.

**Comment by robertahunt** [comment] 2020-05-12 09:44
@Kevindeving good catch. We have been in contact with ENTSOE regarding this, without much luck so far. I think the problem lies with their data provider and these things take some time to sort out. I am closing this in favor of keeping all our related Netherlands woes in #78 . Part of the problem is we do not understand why they have such a high 'fossil gas consumption' and I am not sure if we should trust the production values or the difference between the production and consumption. If you have a source we could use to figure out which it correct, that would be helpful, but please continue this in #78.

**Closed by robertahunt** 2020-05-12 09:44 UTC
