### ISSUE TITLE
ENTSOE: Invalid values for coal and gas Netherlands

### ISSUE THREAD

**Issue by ThierryOllivero** [tmrowco/electricitymap-contrib#78] opened 2016-09-21 18:52 UTC
Basic stuff (total production / total consumption / imports / exports) can be found here: http://energieinfo.tennet.org/dataexport/exporteerdatacountry.aspx

Did not find an actual split by generation type, yet.

**Comment by corradio** [comment] 2016-11-08 18:22
ENTSOE data is lacking production:

![image](https://cloud.githubusercontent.com/assets/1655848/20111464/b4754a60-a5e8-11e6-95c1-a13fc2c0a0be.png)

**Comment by rustyb** [comment] 2017-01-19 15:36
Hi Folks - just to let you know we're looking into the issue with generation per type for the Netherlands on the ENTSO-E transparency platform.

I can confirm that the 1MW values for coal is the same value delivered to us by the dutch TSO('s). Will keep you posted here.

PS. I'm the web guy at ENTSO-E

**Comment by corradio** [comment] 2017-01-27 08:18
Updating this issue: invalid values for gas and coal:

![image](https://cloud.githubusercontent.com/assets/1655848/22364405/9d28bd0c-e471-11e6-8261-1205225abb55.png)

**Comment by corradio** [comment] 2017-03-08 08:48
There's hope:
https://twitter.com/FlorenceKofi/status/839133868322062336

**Comment by MariusKroon** [comment] 2017-06-05 07:50
The Netherlands is still showing up as grey on the map yesterday afternoon and this morning, although there are values available on ENTSO-e for production per type for the Netherlands. 
The production per type bars are correctly showing the values for the respective fuel types, but somehow the calculation for the emission is not working. 

Btw; The bar graph shows question marks for fuel type that are not used in the Netherlands, there are no power plants that run on e.g. Lignite or Oil. ENTSO-e has a specific report available that returns the reported installed capacity per production type [here](https://transparency.entsoe.eu/generation/r2/installedGenerationCapacityAggregation/show) - it might be more graceful to base the overview of total installed capacities on this data instead of the static file in the config folder.

**Comment by corradio** [comment] 2017-06-06 07:50
Hi @MariusKroon,

We manually disabled NL for now. Where do you see production values from ENTSOE? We still miss proper values for coal, nuclear and gas, see https://transparency.entsoe.eu/generation/r2/actualGenerationPerProductionType/show?name=&defaultValue=false&viewType=TABLE&areaType=CTY&atch=false&datepicker-day-offset-select-dv-date-from_input=D&dateTime.dateTime=06.06.2017+00:00|CET|DAYTIMERANGE&dateTime.endDateTime=06.06.2017+00:00|CET|DAYTIMERANGE&area.values=CTY|10YNL----------L!CTY|10YNL----------L&productionType.values=B01&productionType.values=B02&productionType.values=B03&productionType.values=B04&productionType.values=B05&productionType.values=B06&productionType.values=B07&productionType.values=B08&productionType.values=B09&productionType.values=B10&productionType.values=B11&productionType.values=B12&productionType.values=B13&productionType.values=B14&productionType.values=B20&productionType.values=B15&productionType.values=B16&productionType.values=B17&productionType.values=B18&productionType.values=B19&dateTime.timezone=CET_CEST&dateTime.timezone_input=CET+(UTC+1)+/+CEST+(UTC+2)

Regarding capacity, feel free to submit a pull request that updates the config file based on https://transparency.entsoe.eu/generation/r2/installedGenerationCapacityAggregation/show.

**Comment by MariusKroon** [comment] 2017-06-06 09:08
Hi @corradio ,

I did some further investigation, the reporting of coal production does seem to be very inconsistent indeed. The 24th of May 2017 does show generation for fossil hard coal on ENTSO-e, all hours less than 100MW. The next day shows all hours as 'n/e' again, so you are correct in saying that the proper, consistent values are missing. 

Regarding the nuclear generation, I know that there is only 1 active power plant in NL, and from the messages on the website of the owner it seems that it is undergoing maintenance until at least the 14th of July, 2017. ( https://www.pzem.nl/trading/assets/remit ) . Maintenance started on the 21st of April of 2017, so it does unfortunately not account for non reported generation before that date. 

I was calculating based on the percentages of total power generated that is visible in the bar chart, and doing so, I did come up to 100%. This 100% is however based on the fuel types and imports that are available in the chart, not as a percentage of the total consumption/load of that moment. 

I will put in a request for the total available capacity - I think it will show a more correct overview of the total available capacity per country, especially the total capacity for wind is changing quickly these days.

**Comment by MariusKroon** [comment] 2017-06-06 09:12
One extra remark on the coal production: RWE is the owner of some coal-fired plants in the Netherlands, and on their website there are actual production numbers available. ( https://www.rwe.com/web/cms/en/59926/transparency-drive/central-europe/utilization/power-generation-review/ ) Amer 9 and Eemshaven A/B are located in the Netherlands . 

Somehow these messages are not published towards or processed on the ENTSO-e platform.

**Comment by corradio** [comment] 2017-06-06 09:31
Thanks for the analysis @MariusKroon. @Dalius-ENTSO-E do you have any more insights on this case?

**Comment by janvlug** [comment] 2017-08-24 15:18
I asked via this web form for real time electricity production in the Netherlands:
http://www.energieakkoordser.nl/doen/contact/formulier.aspx

In the reply I got they referred to this Dutch site:
https://jaspervis.wordpress.com/2017/07/02/hoeveel-duurzame-stroom-wordt-er-vandaag-opgewekt-in-nederland/

And they stated that they are working towards real time information, but that it still takes many steps.

Furthermore, I found this web site:
http://www.windparkkubbeweg.nl/molens.php

**Comment by Freeb0** [comment] 2017-09-04 13:50
I asked Tennet for the real time production data and I also found this one : http://energieopwek.nl/

**Comment by corradio** [comment] 2017-09-04 16:50
It does not contain fossil fuels so we only have incomplete information and
can thus not compute co2 intensity :/

**Comment by janvlug** [comment] 2017-10-07 11:49
I contacted via Twitter (https://twitter.com/TenneTTSO/status/914746176351735809) Tennet TSO to ask for the required information. They redirected met to TenneT CCC to whom I sent an email to ask for the required info.

**Comment by corradio** [comment] 2017-10-07 12:22
Thanks for helping out. Keep us updated.

Olivier

**Comment by corradio** [comment] 2017-11-22 11:34
Hi @janvlug , did you get any insights?

**Comment by corradio** [comment] 2017-12-07 16:04
I got insights today that Tennet is aware of the issue and working on it.

**Comment by corradio** [comment] 2017-12-08 08:13
@Dalius-ENTSO-E the values for coal and gas are incorrect. We know the data providers are working on this, but in the meantime, I think ENTSOE should report those values as missing instead of the incorrect numbers they currently provide.

**Comment by Dalius-ENTSO-E** [comment] 2017-12-08 08:45
personally, I agree. However, data providers decided that TP should not validate correctness of values and data quality is the responsibility of data providers. TP should publish whatever data provider reports. Data quality check is implemented for few data items, however TP generate only warnings for data providers. 
We can't show values as missing if values are delivered. I will check also with TenneT NL when data will be correct.

**Comment by corradio** [comment] 2017-12-08 08:51
Thank you for your clarification. I understand.

**Comment by alixunderplatz** [comment] 2018-02-03 14:41
Some news on the Netherlands:

It seems that some data has been added for generation values of the past to ENTSO-E. I had never looked at the data in detail, but here is a summary:

As of today (3rd Feb), there is trustworthy data up to the 12th Jan in the thousands-MW-range instead of the two-digit-MW-range for today's generation from gas. 
Nuclear, wind, solar and biomass also look fine for data before this date (delay of 3 weeks). However, hard coal is missing in generation by type.
But hard coal is included in "generation by unit" with the usual delay of 5 days. I doubt this represents all the hard coal units, but haven't checked this in detail.

It is going in the right direction. So we have to keep an eye on any possible progress in the next weeks.

For cross-checking - in case the live data will be valid - here are some sources:
Tennet NL is still publishing data on their total actual generation without categories:
https://www.tennet.eu/nl/elektriciteitsmarkt/data-dashboard/productie/

Some [generating companies](https://www.eex-transparency.com/homepage/power/the-netherlands) are reporting live actual generation to EEX transparency platform, but this only covers 1/3 to 1/2 of total generation:
https://www.eex-transparency.com/homepage/power/the-netherlands/production/usage/actual-production-100-mw-

**Comment by alixunderplatz** [comment] 2018-02-14 12:47
NL's trustworthy generation data on Entso-e is still 18 days behind. Still unusable for the live map and missing hard coal generation.

But I had a go on putting data from ENTSO-E and EEX (some hard coal available!) and net exchange balance into one chart.
There is a gap of 1-3 GW of missing generation.

![image](https://user-images.githubusercontent.com/25743609/36204928-4ab1f74c-118d-11e8-8353-9d721ac92187.png)

**Comment by corradio** [comment] 2018-02-14 14:25
wow! Super nice to know it is available historically

**Comment by corradio** [comment] 2018-02-22 15:09
Update:

![image](https://user-images.githubusercontent.com/1655848/36546089-c21d87ca-17ea-11e8-8e34-eec7a4d26c47.png)

**Comment by alixunderplatz** [comment] 2018-03-27 13:41
Thinking out loud: Isn't this sort of a violation by the responsible utilities of The Netherlands already?

Here is the legal directive: [COMMISSION REGULATION (EU) No 543/2013](http://eur-lex.europa.eu/LexUriServ/LexUriServ.do?uri=OJ:L:2013:163:0001:0012:EN:PDF)

and here are some useful quotes from it:

General stuff:
> Article 1
Subject matter
This Regulation lays down the minimum common set of data relating to generation, transportation and consumption of electricity to be made available to market participants. It also provides for a central collection and publication of the data.


The primary owners shall submit the data with required quality within required time, which they obviously don't/can't, else we wouldn't face this issue:
> Article 4
> Submission and publication of data
> 1. **Primary owners of data** shall submit data to TSOs in accordance with Articles 6 to 17. They **shall ensure that the data they provide to TSOs, or where provided for in accordance with paragraph 2 to data providers, are complete, of the required quality and provided in a manner that allows TSOs or data providers to process and deliver the data** to the ENTSO for Electricity **in sufficient time** to allow the ENTSO for Electricity to meet its obligations under this Regulation in relation to the timing of the publication of information.
> TSOs, and where relevant data providers, shall process the data they receive and provide them to the ENTSO for Electricity in due time for publication.


Per-type-generation shall be submitted no later than 1 hour after the operational period.
> Article 16
> Actual generation
> 1. For their control areas, TSOs shall calculate and provide the following information to the ENTSO for Electricity:
> (a) actual generation output (MW) per market time unit and per generation unit of 100 MW or more installed generation capacity;
> **(b) aggregated generation output per market time unit and per production type;**
> (c) actual or estimated wind and solar power generation (MW) in each bidding zone per market time unit;
[...]
> 2. The information laid down:
> (a) in point (a) of paragraph 1 shall be published five days after the operational period;
> **(b) in point (b) of paragraph 1 shall be published no later than one hour after the operational period;EN 15.6.2013 Official Journal of the European Union L 163/9**
> (c) in point (c) of paragraph 1 shall be published no later than one hour after the operational period and be updated on the basis of measured values as soon as they become available. The information shall be provided for all bidding zones only in Member States with more than 1 % feed-in of wind or solar power generation per year or for bidding zones with more than 5 % feed-in of wind or solar power generation per year;


Finally, an article on liability ... which is limited:
> Article 18
> Liability
> The liability of the primary owner of the data, the data provider and the ENTSO for Electricity under this Regulation shall be **limited to cases of gross negligence and/or wilful misconduct.**

**Comment by janvlug** [comment] 2018-03-27 14:54
I sent an email to the [SER](https://www.energieakkoordser.nl/energieakkoord.aspx) to ask their reaction on the comment above.

**Comment by janvlug** [comment] 2018-03-27 15:11
I sent a similar request to the Dutch minister of economical affairs and climate, Eric Wiebes.

**Comment by alixunderplatz** [comment] 2018-03-28 21:56
There is a monthly report by Dr. Martien Visser / Hanze University of Applied Sciences Groningen for their Energy Transition Centre _EnTranCe_, which seems to have generation time series and mix breakdown - various sources are mentioned below the graphs.

Find the reports here:
http://en-tran-ce.org/newsletter-renewable-energy-in-the-netherlands/

This image is in the report for [February 2018](http://en-tran-ce.org/wp-content/uploads/2015/07/Renewable-Energy-in-NL-February-2018.pdf). The resolution is on hourly level.
![image](https://user-images.githubusercontent.com/25743609/38056503-dc2137a4-32dc-11e8-872b-15dc82eec4bc.png)

On the very last slide it says, the available data from the sources isn't complete, so some of it is approximated and scaled (I assume gas and biogas, maybe coal). This data and its quality looks absolutely superior to everything I had seen so far.
@corradio @brunolajoie I think this could be something to fill the database while no live-data is available! The earliest report I could find on the site with that hourly data is for the year 2014.

**Comment by brunolajoie** [comment] 2018-03-29 07:02
Super nice! I see two steps forward (correct me if i'm wrong)
1. Try to use this deck to set up a fixed carbon intensity of export for NL
2. Contact them to see if they have raw hourly resolution dataset available somewhere for us (from what i've seen, it's only pictures)

**Comment by alixunderplatz** [comment] 2018-03-29 07:56
right! :) 2.) from the raw data you'll see how strong the domestic carbon intensity will fluctuate over time to determine 1.) in #1277 - I think it could be a significant up-and-down due to wind and solar.

**Comment by brunolajoie** [comment] 2018-03-29 08:23
I'll contact them. If no/negative answer within a week, I suggest to try to add mean intensity values derived from annual aggregates

**Comment by corradio** [comment] 2018-03-31 12:30
@brunolajoie let's use #1277 for the fixed carbon intensity, and keep this issue open for real-time data.

**Comment by alixunderplatz** [comment] 2018-09-18 19:49
Any news from TenneT?

![image](https://user-images.githubusercontent.com/25743609/45711627-76559000-bb8a-11e8-995c-c320464e69e5.png)

![image](https://user-images.githubusercontent.com/25743609/45712136-d26ce400-bb8b-11e8-85d0-c1e7dde982ad.png)

**Comment by corradio** [comment] 2018-09-18 20:09
No news on my side unfortunately..

**Comment by jasonrwang** [comment] 2018-10-15 14:31
Hi, I just wanted to add some more bad news to this conversation. At the moment (2018-10-15 16:26), the [ENTSOE wind generation data](https://transparency.entsoe.eu/generation/r2/actualGenerationPerProductionType/show?name=&defaultValue=true&viewType=TABLE&areaType=BZN&atch=false&datepicker-day-offset-select-dv-date-from_input=D&dateTime.dateTime=15.10.2018+00:00|CET|DAYTIMERANGE&dateTime.endDateTime=15.10.2018+00:00|CET|DAYTIMERANGE&area.values=CTY|10YNL----------L!BZN|10YNL----------L&productionType.values=B01&productionType.values=B02&productionType.values=B03&productionType.values=B04&productionType.values=B05&productionType.values=B06&productionType.values=B07&productionType.values=B08&productionType.values=B09&productionType.values=B10&productionType.values=B11&productionType.values=B12&productionType.values=B13&productionType.values=B14&productionType.values=B20&productionType.values=B15&productionType.values=B16&productionType.values=B17&productionType.values=B18&productionType.values=B19&dateTime.timezone=CET_CEST&dateTime.timezone_input=CET+(UTC+1)+/+CEST+(UTC+2)) for The Netherlands seems to have cut out. Furthermore, they seem to have generation capacity for the future under the solar section (where even until one hour past sunset, there's supposed to be 5 MW of generation). Maybe forecasts are now part of ENTSOE's transparency platform?

<img width="998" alt="image" src="https://user-images.githubusercontent.com/6628281/46957225-69e42a80-d097-11e8-9ed3-6fc3dbf6a168.png">

**Comment by alixunderplatz** [comment] 2019-03-20 20:22
It's been over two years now since this data quality issue has been discussed.
electricityMap is not the only project depending on correct data. Market participants, other transparency platforms, scientists and the interested people of The NL and the EU also have the right to get informed about the near-real-time generation mix in The Netherands.

Once again, here's a summary of the recent status as per 20 March 2019:
- the data provided to ENTSO-E by the TSO TenneT still is NOT delivered as required (max. 1h behind real-time, see my [comment](https://github.com/tmrowco/electricitymap-contrib/issues/78#issuecomment-376529372) above)
- the only usable production types for real-time are "wind offshore" and "wind onshore"
_________
- solar data is no more provided on intraday basis in real-time (we used to have this in the past!), but on the next day
_________
- coal and gas are still reported in a very bad quality with clearly wrong values of 0-40 Megawatt instead of 3-10 Gigawatt (they fill the residual load)
_________
- nuclear is not reported at all in real-time (1 reactor / ~500 MW)
- nuclear is only reported the next day in the "per unit" tab for NL
_________
- absolutely no data for production from coal in the "per production type" tab
- some coal data in the "per generation unit" tab for NL, but probably not complete on the next day
_________
- some gas data in the "per generation unit" tab for NL, but pobably not complete on the next day
_________
- the "per production type" data on ENTSO-E is partially refilled in a second step 20 days later with categories "nuclear" and "gas", but absolutely no coal data
_________
If you want to have a look at the data yourself: [HERE IS THE LINK TO THE TRANSPARENCY PLATFORM](https://transparency.entsoe.eu/generation/r2/actualGenerationPerProductionType/show?name=&defaultValue=false&viewType=GRAPH&areaType=BZN&atch=false&datepicker-day-offset-select-dv-date-from_input=D&dateTime.dateTime=20.03.2019+00:00|CET|DAYTIMERANGE&dateTime.endDateTime=20.03.2019+00:00|CET|DAYTIMERANGE&area.values=CTY|10YNL----------L!BZN|10YNL----------L&productionType.values=B01&productionType.values=B02&productionType.values=B03&productionType.values=B04&productionType.values=B05&productionType.values=B06&productionType.values=B07&productionType.values=B08&productionType.values=B09&productionType.values=B10&productionType.values=B11&productionType.values=B12&productionType.values=B13&productionType.values=B14&productionType.values=B20&productionType.values=B15&productionType.values=B16&productionType.values=B17&productionType.values=B18&productionType.values=B19&dateTime.timezone=CET_CEST&dateTime.timezone_input=CET+(UTC+1)+/+CEST+(UTC+2))


In the history of this project, we have been the "transparency data quality cops" many times and always got help from the friendly and helpful folks at ENTSO-E and various responsible data providers / Transmission system operators. I am sure we can still manage to get this fixed by the responsible authorities, especially cosidering the ever growing number of electricityMap users and interested people. :) 
Probably, it's just a tiny error in an outdated .csv file or a spreadsheet somewhere in the whole process which is causing these issues and data errors...

Time to make another attempt to get this fixed?

**Comment by corradio** [comment] 2019-03-20 20:25
@Dalius-ENTSO-E can you help us make our voice be heard?

**Comment by Dalius-ENTSO-E** [comment] 2019-03-20 20:34
Hi,
Sure. Thanks for very interesting and very good observations. I will analyse all these comments very detail tomorrow and then I will let you know.

**Comment by Dalius-ENTSO-E** [comment] 2019-03-22 07:54
Hi,
Majority of these issues are related no producers. TenneT NL can't influence them. I received the following feedback and clarification:
Currently TenneT and the NRA are working together on this topics. The following steps are defined to create more quality in this:
1.	Create new publication for art. 16.1.b&c => planning live March 2019
a.	Data first will be published all in "others" as being none identifiable.
b.	Based on delivered Master data from Market Participants the data will be filled to the correct "fuel type", depending on Market Participants
c.	Solar data will be included after point 2 near real time (still a estimation, none real time data available).
2.	Data published for wind and solar forecast, change of data provide => planning live week 15

Best regards,
Dalius

**Comment by Dalius-ENTSO-E** [comment] 2019-03-22 07:55
Local National Regulator: www.acm.nl

**Comment by alixunderplatz** [comment] 2019-04-24 21:06
Hey guys, some very good news on this topic!
The data on ENTSOE for NL looks wayyyy better than before! :)


Here is what it looks like for today:
We now have some data for gas (green), nuclear (grey), coal (purple) and other (blue)!
However, solar is still missing, and wind just seems to be a bit too low at the moment.

![image](https://user-images.githubusercontent.com/25743609/56692962-a39b8b00-66e3-11e9-8068-7ddaa4013c20.png)
_____________________________

Solar was included on the 20th April and the days before (upper purple):

![image](https://user-images.githubusercontent.com/25743609/56693150-05f48b80-66e4-11e9-83da-81a767773795.png)
_______________________________________

Here is what the total generation+exchange balance looks like compared to the total load for today (24th April): production "gap" of about 2.5 to 3.5 GW for each hour. So there is a gap of 30-35% due to the missing production, but maybe this will improve soon?
![image](https://user-images.githubusercontent.com/25743609/56692694-0d676500-66e3-11e9-86de-4f0ed9b2642e.png)

I'm very happy to see these improvements 👍  & I hope we can close this issue soon 🙏 :)

**Comment by eoinbutler** [comment] 2019-05-21 16:51
The NL parser seems to not have taken account of the new improvements to ENTSOE for NL. Is there someone working on it, or would you welcome a pull request?

**Comment by alixunderplatz** [comment] 2019-05-21 20:07
@eoinbutler The parser ignores the improvements on ENTSOE at the moment and just takes into account wind+solar, load and exchanges, to calculate the missing share of production for NL.
Wind (only a share reported) and solar (gone missing completely) got worse in the current reporting on ENTSOE, but let's hope it will be improved soon. 😐 -> 😀
The reported generation on ENTSOE, however, is too low to fill the gap to the demand of NL. We could, of course, take all available production into account, but then I'd have no idea what carbon intensity we should assign to "unknown".
One thing we could surely add to the graph is nuclear, as there is only one unit with ~500-600 MW, afaik.

Here is what production in NL looked like  today on ENTSOE  :

![image](https://user-images.githubusercontent.com/25743609/58126804-1715b700-7c14-11e9-8172-f7a580ead486.png)

**Comment by eoinbutler** [comment] 2019-05-22 08:57
How do you assign the carbon intensity to "unknown" at the moment?

**Comment by jarek** [comment] 2019-05-22 12:34
It was computed based on 2017-2018 annual generation, see https://github.com/tmrowco/electricitymap-contrib/issues/1277

It is subsequently input in https://github.com/tmrowco/electricitymap-contrib/blob/master/config/co2eq_parameters.json#L475-L480

**Comment by alixunderplatz** [comment] 2019-10-01 23:14
Data for the Netherlands on ENTSOE is almost looking good now ;)
We need to check in the next days, whether the balance of production and exchanges nearly matches the load. If so, we can finally activate the entire production mix for the NL ;)

@Dalius-ENTSO-E for your info: currently, a "fossil gas consumption" of up to 1,7 GW is reported for the NL. I guess that's a bug, and the reported amount also belongs to gas production? Can you check? Thanks! :)

![image](https://user-images.githubusercontent.com/25743609/66006889-91065880-e4b0-11e9-882e-33c7ca5e42eb.png)

**Comment by Salix-Knot** [comment] 2019-10-15 09:31
As for the source 'Unkown", these are the latest numbers for the Netherlands, Jan-Aug 2019:
Gas: 56.6%
Coal: 14.2%
CO2: 370 gr/kWh

![EG2TkNyXkAAqR8W](https://user-images.githubusercontent.com/56584578/66818970-6f8c7e80-ef3e-11e9-998d-e511a9ca86bd.jpg)

See: https://twitter.com/BM_Visser/status/1183786282704691203
Note:  Martien Visser runs Entrance's monthly 'Renewable Energy in the Netherlands'
https://www.en-tran-ce.org/en/research/renewable-energy-in-the-netherlands/

**Comment by corradio** [comment] 2019-10-15 09:35
@alixunderplatz (and others in this thread): does this mean we're ready to shift over to ENTSOE data?

**Comment by ThierryOllivero** [comment] 2019-10-15 09:40
I looked at the last days and it seems good to me.

**Comment by alixunderplatz** [comment] 2019-10-16 22:49
@corradio I think so, yes :))))

**Comment by rhebly** [comment] 2020-02-20 10:08
Hi everyone in this thread, is it closed successfully? I am looking at NL renewables from ENTSOe that come from Tennet, but it seems that both Onshore wind and Solar actuals are structurally mismatched against the forecasts. Also when comparing to https://energieopwek.nl/#Energieproductie-getallen, it is clear that ENTSOe actuals are still way off. Do you find the same?

**Comment by alixunderplatz** [comment] 2020-02-20 19:30
Hi @rhebly, I have similar feelings about solar and wind for NL.
I took quite a while to get the correct data for the conventional fuels reported at all.
I think we should consider taking wind, solar + biomass from energieopwek.nl

There is another big bug on entsoe: fossil gas consumption is reported with up to 2200 MW. I think this part should also go into "fossil gas generation" as a positive value. I mentioned that issue in my comment from 2nd October 2019.
Can someone from the tmrow team report this to ENTSO-E?
![image](https://user-images.githubusercontent.com/25743609/74970824-5b421c00-541f-11ea-9c00-30480334d61f.png)

**Comment by corradio** [comment] 2020-02-21 08:00
I'm reopening the issue and will let @robertahunt and @tth4vb follow up

**Comment by robertahunt** [comment] 2020-02-24 12:08
Sent a mail to one of our contacts in ENTSO-E. I'll update when we get a reply.

**Comment by corradio** [comment] 2020-12-22 14:18
@tth4vb @Kongkille what is the outstanding work remaining to be done on NL?

**Comment by Kongkille** [comment] 2021-02-19 09:14
It seems that we can close it for now :)

**Closed by Kongkille** 2021-02-19 09:14 UTC
Labels: parser
