### ISSUE TITLE
German translation on energy legend is cut off

### ISSUE THREAD

**Issue by tth4vb** [tmrowco/electricitymap-contrib#2252] opened 2020-02-26 09:08 UTC
in the legend for energy generation when the map is in German, the ‘B’ is missing where it says ‘atteriespeicher’, instead of Batteriespeicher. This is because the length of the text is too long compared to the column size.

**Comment by robertahunt** [comment] 2020-03-27 12:55
@fbarl Is this still an issue? It works for me on Firefox/ubuntu. 

![image](https://user-images.githubusercontent.com/13189214/77758075-a52bac80-7032-11ea-8a09-948ab6c0358d.png)

**Comment by fbarl** [comment] 2020-03-27 17:03
Yes, it works on my Ubuntu Chrome as well actually.

@tth4vb are you able to reproduce it still? If yes, please share a screenshot and some basic info about your browser. It's possible I accidentally fixed it in https://github.com/tmrowco/electricitymap-contrib/pull/2263 :slightly_smiling_face:

**Comment by fbarl** [comment] 2020-03-30 12:38
Closing as the issue seems to have been fixed - @tth4vb feel free to reopen if the problem persists or reappears.

**Closed by fbarl** 2020-03-30 12:38 UTC
Labels: bug 🐞, frontend 🎨
