### ISSUE TITLE
Add carbon intensity for for Gulf countries so they show up on the map

### ISSUE THREAD

**Issue by q--** [tmrowco/electricitymap-contrib#2397] opened 2020-04-23 08:59 UTC
In #2357 I reported finding consumption for Gulf Cooperation Council countries (United Arab Emirates, Bahrain, Saudi Arabia*, Oman*, Qatar, and Kuwait**). In #2360 I added a parser, and bounding boxes were added by @robertahunt in  #2366.

The countries haven't shown up on the map yet, though, which I assume is because they don't have CO2 intensity parameters net. I don't know how to calculate those.

Maybe someone can do do the math on that so these countries will show up on the map? Thanks in advance

<sub>* GCCIA currently (still) isn't reporting data on Oman and Saudia Arabia; the parser will return data for them once it shows up again at the GCCIA site.</sub>
<sub>** Kuwait already had a working parser, `KW.py`, which continues to be used. </sub>

**Comment by jarek** [comment] 2020-04-23 12:55
Does the GCCIA site provide yearly statistics on fuel/sources of the electricity generated in each country?

**Comment by q--** [comment] 2020-04-23 20:22
Haven't seen it yet. The latest annual report on the home page is from 2018 anyway (an all-images PDF, good luck searching that), so it's probably easier to just get the info from the IEA as it was done for Kuwait.

**Comment by q--** [comment] 2020-04-24 18:46
Generation in GWh, 2017, IEA data

Note that the IEA site has a bug where it switches to the wrong graph, I used the "Electricity generation by source"  graph

[UAE](https://www.iea.org/data-and-statistics?country=UAE&fuel=Electricity%20and%20heat&indicator=Electricity%20generation%20by%20source)

```
Oil 1530
Natural gas 132231
Solar PV  535
Solar thermal 257
```

[Oman](https://www.iea.org/countries/oman)
```
Oil 1038
Natural gas 35088
```

[Qatar](https://www.iea.org/countries/qatar)
```
Natural gas 45555
```

[Saudi Arabia](https://www.iea.org/countries/saudi-arabia)
```
Oil 125860
Natural gas 221836
```

[Bahrain](https://www.iea.org/countries/bahrain)
```
Natural gas 29223
Oil 2
```

**Comment by q--** [comment] 2020-04-24 19:17
Found some possibly relevant data on the UAE

Data is from the Dubai Electricity and Water Authority, so probably not the entire UAE

[Gross power generation by month and plant for 2018](https://data.bayanat.ae/en_GB/dataset/dewa-gross-power-generation-mwh/resource/49bb88a7-2351-439c-b047-712253d978b4)

[The same data for 2019, as well as consumption etc](https://www.dubaipulse.gov.ae/data/dewa-consumption/dewa_gross_power_generation_mwh-open?organisation=dewa&service=dewa-consumption)

**Comment by q--** [comment] 2020-04-24 19:38
## Data for the entire UAE
[Installed capacity for the UAE as of 2016](https://data.bayanat.ae/en_GB/dataset/installed-capacity-of-electricity-generation-plants-by-generator-type/resource/db5b872a-f04e-427c-b81a-054ebe9243f6)

[Quantity of Electriciy production by Renewable Energy Type](https://data.bayanat.ae/en_GB/dataset/quantity-of-electricity-production-by-renewable-energy-type/resource/7df45611-eff7-4c1f-94f4-cdaa6030f5b5) but last updated 2017 so no better than the IEA data

**Comment by robertahunt** [comment] 2020-04-26 13:25
Hi q--, I think it is a great initiative to update the co2 parameters for these regions if you can find a source for them! But the reason these countries haven't shown up on the map is not because we are missing co2 parameters - we have defaults for those. It is because what we use to calculate the 'consumption' map is the production by fuel type, and the imports into a region (including the carbon intensity of those imports). What we have done previously (you can see the parsers for japan, for example), is using the import data we can calculate the production for each region (classified as unknown), and from there we can run our flow model to calculate the emissions of the system. Putting all the production on 'unknown' is definitely not preferred, but in cases where there is no other option, that is what we do.

You could do this production-approximation with these countries, but I think we are missing the import and export data, which is essential for such a calculation. Sorry :(.

**Comment by corradio** [comment] 2020-06-09 13:51
@q-- unfortunately I will have to close this issue as there's nothing we can do without real-time data.
However, we're extremely grateful for the research you did. Even if the issue is closed, I'm confident we will use this knowledge in the future as soon as some more data comes up, or if we need to add fallback intensities to the system.

**Closed by corradio** 2020-06-09 13:51 UTC

**Comment by q--** [comment] 2020-06-19 22:34
Screenshots of the app ![GCCIA app screenshot](https://lh3.googleusercontent.com/5vue_deaCqBnKmCrmX9m6V6zVbjZTxR_IHDh6fqs79C-Tbg8lMkBZV3C6Pju2bKJ-Y8=w1908-h953) show it has some information on "interchange". (Haven't installed, though)

If it were possible to extract this data, would it be enough to have those countries show up on the map?

**Comment by q--** [comment] 2020-07-15 19:55
Turns out the IEA has electricity import/export data as well (its in [ktoe](https://en.wikipedia.org/wiki/Tonne_of_oil_equivalent), so it'll have to be converted to MWh first)

https://www.iea.org/data-and-statistics?country=UAE&fuel=Imports%2Fexports&indicator=Electricity%20imports%20vs.%20exports, make sure to switch to 'electricity imports/exports'

At least for the UAE imports in 2017 were pretty insignificant
