### ISSUE TITLE
JP-SK: 'NoneType' object does not support item assignment

### ISSUE THREAD

**Issue by brunolajoie** [tmrowco/electricitymap-contrib#1695] opened 2018-11-30 08:05 UTC
Errror seen on [kibana](https://kibana.electricitymap.org/app/kibana#/discover/1710fdd0-2460-11e8-a779-9d01de8d7a71?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:now-1h,mode:quick,to:now))&_a=(columns:!(level,extra.key,message),filters:!(('$state':(store:appState),exists:(field:level),meta:(alias:!n,disabled:!f,index:'93e631f0-245f-11e8-a779-9d01de8d7a71',key:level,negate:!f,type:exists,value:exists)),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'93e631f0-245f-11e8-a779-9d01de8d7a71',key:level,negate:!t,params:(query:INFO,type:phrase),type:phrase,value:INFO),query:(match:(level:(query:INFO,type:phrase))))),index:'93e631f0-245f-11e8-a779-9d01de8d7a71',interval:auto,query:(language:lucene,query:''),sort:!('@timestamp',desc)))
>traceback (most recent call last):
  File "/home/feeder/lib/fetch_data.py", line 175, in launch_parsers
    objs = res.get(timeout)
  File "/usr/local/lib/python3.6/multiprocessing/pool.py", line 670, in get
    raise self._value
  File "/usr/local/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/feeder/lib/fetch_data.py", line 173, in <lambda>
    **parser_kwargs))
  File "/home/contrib/parsers/JP.py", line 57, in fetch_production
    df2 = occtonet.fetch_exchange(zone_key, zone, target_datetime)
  File "/home/contrib/parsers/occtonet.py", line 92, in fetch_exchange
    Headers_1 = get_request_token(r, Headers_1, Cookies)
  File "/home/contrib/parsers/occtonet.py", line 237, in get_request_token
    payload['fwExtention.actionSubType']='ok'
TypeError: 'NoneType' object does not support item assignment

**Comment by systemcatch** [comment] 2018-12-02 11:13
I see quite a few errors like this for most of the JP zones, all of them happen when the exchange/exchange forecast functions are called in occtonet.py.

Looking at the code I think the problem is on https://github.com/tmrowco/electricitymap-contrib/blob/master/parsers/occtonet.py#L225. The request errors for whatever reason and the get_headers function returns None which then causes the error in the logger.

We first need to make sure the error message is caught by the logger, then figure out what to do about it.

**Comment by systemcatch** [comment] 2018-12-02 12:04
Having said that maybe it would be better to just raise an Exception here since it's never going to work when the request returns an error.

**Comment by systemcatch** [comment] 2018-12-03 17:18
So errors are now being logged properly, we see this error 9 times in the past 24 hours.

```python
RuntimeError: Headers not available due to [{'labelText': [], 'msgFormat': 'システムに異常が発生しました。内容確認後、システム管理者に連絡して下さい。', 'msgId': 'BS0002480G'}]
```

translated to english

```python
RuntimeError: Headers not available due to [{'labelText': [], 'msgFormat': 'An error occurred in the system. After checking the contents, please contact the system administrator. ',' msgId ':' BS0002480 G '}]
```

which is not very helpful. :roll_eyes: 

There's some other errors as well that keep cropping up.

59 times in 7 days.

```python
Traceback (most recent call last):
  File "/home/feeder/lib/fetch_data.py", line 175, in launch_parsers
    objs = res.get(timeout)
  File "/usr/local/lib/python3.6/multiprocessing/pool.py", line 670, in get
    raise self._value
  File "/usr/local/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/feeder/lib/fetch_data.py", line 173, in <lambda>
    **parser_kwargs))
  File "/home/contrib/parsers/JP.py", line 54, in fetch_production
    df = fetch_consumption_df(zone_key, target_datetime)
  File "/home/contrib/parsers/JP.py", line 120, in fetch_consumption_df
    encoding='shift-jis')
  File "/usr/local/lib/python3.6/site-packages/pandas/io/parsers.py", line 709, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/usr/local/lib/python3.6/site-packages/pandas/io/parsers.py", line 455, in _read
    data = parser.read(nrows)
  File "/usr/local/lib/python3.6/site-packages/pandas/io/parsers.py", line 1069, in read
    ret = self._engine.read(nrows)
  File "/usr/local/lib/python3.6/site-packages/pandas/io/parsers.py", line 1839, in read
    data = self._reader.read(nrows)
  File "pandas/_libs/parsers.pyx", line 902, in pandas._libs.parsers.TextReader.read
  File "pandas/_libs/parsers.pyx", line 924, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas/_libs/parsers.pyx", line 978, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 965, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 2208, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: Expected 1 fields in line 174, saw 2
```

21 in 7 days.

```python
Traceback (most recent call last):
  File "/home/feeder/lib/fetch_data.py", line 175, in launch_parsers
    objs = res.get(timeout)
  File "/usr/local/lib/python3.6/multiprocessing/pool.py", line 670, in get
    raise self._value
  File "/usr/local/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/feeder/lib/fetch_data.py", line 173, in <lambda>
    **parser_kwargs))
  File "/home/contrib/parsers/JP.py", line 54, in fetch_production
    df = fetch_consumption_df(zone_key, target_datetime)
  File "/home/contrib/parsers/JP.py", line 120, in fetch_consumption_df
    encoding='shift-jis')
  File "/usr/local/lib/python3.6/site-packages/pandas/io/parsers.py", line 709, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/usr/local/lib/python3.6/site-packages/pandas/io/parsers.py", line 449, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/usr/local/lib/python3.6/site-packages/pandas/io/parsers.py", line 818, in __init__
    self._make_engine(self.engine)
  File "/usr/local/lib/python3.6/site-packages/pandas/io/parsers.py", line 1049, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/usr/local/lib/python3.6/site-packages/pandas/io/parsers.py", line 1695, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 565, in pandas._libs.parsers.TextReader.__cinit__
pandas.errors.EmptyDataError: No columns to parse from file
```

**Comment by corradio** [comment] 2019-09-30 23:34
@systemcatch should I close this?

**Comment by systemcatch** [comment] 2019-10-02 17:24
@corradio yeah let's close this.

**Closed by systemcatch** 2019-10-02 17:24 UTC
Labels: bug 🐞, parser
