### ISSUE TITLE
Données Suisse

### ISSUE THREAD

**Issue by fcimballi** [tmrowco/electricitymap-contrib#2824] opened 2020-12-01 13:54 UTC
Bonjour,
Il est souvent noté Données temporairement non disponibles pour la Suisse. Pourquoi ?

**Comment by jarek** [comment] 2020-12-02 03:16
Sorry, in English: it looks like official data published is significantly incomplete. You might get some information from the past issue: https://github.com/tmrowco/electricitymap-contrib/issues/892

**Comment by corradio** [comment] 2020-12-22 13:17
Closing as this is a duplicate of #892

**Closed by corradio** 2020-12-22 13:17 UTC
