### ISSUE TITLE
Transition Error Fr <-> DE 

### ISSUE THREAD

**Issue by Spanni26** [tmrowco/electricitymap-contrib#2995] opened 2021-02-13 19:02 UTC
The map shows an import from FR -> DE with the arrows, text says "Export from DE to FR".

![grafik](https://user-images.githubusercontent.com/11832988/107858808-6a8f5600-6e36-11eb-9f3a-8c9c8e2740be.png)

**Comment by jarek** [comment] 2021-02-14 01:56
Hm... works for me now, reads same as in English and matches the arrow:

![de](https://user-images.githubusercontent.com/47415/107866350-d2956a80-6e3d-11eb-95bc-88a6987eb4bb.png)
![en](https://user-images.githubusercontent.com/47415/107866349-d1fcd400-6e3d-11eb-8937-092befed9e67.png)

Did you have the window or app open for a long time before this happened, by any chance?

**Comment by madsnedergaard** [comment] 2021-02-15 09:37
I also can't reproduce this, but thanks for reporting it.

Let me know if you still have this problem @Spanni26, otherwise I think we can close it as a minor one-off bug and keep an eye on it and see if there's a general pattern to it :)

**Comment by madsnedergaard** [comment] 2021-02-19 09:46
Closing this, feel free to reopen if the problem reappears.

**Closed by madsnedergaard** 2021-02-19 09:46 UTC
